name: ci
on:
     pull_request:
          branches: [develop]

jobs:
     first-job:
          runs-on: ubuntu-latest
          steps:
               - uses: actions/checkout@v1
               - name: use node js
                 uses: actions/setup-node@v1
                 with:
                      node-version: '12.x'
               - run: npm install
               - run: npm run format:check
               - run: npm test -- --coverage
                 env:
                      CI: true
