name: ci
on:
     pull_request:
          branches: [develop,master]
     push:
          branches: [develop,master]

jobs:
     first-job:
          runs-on: ubuntu-latest
          steps:
               - uses: actions/checkout@v1
               - name: cache add
                 uses: actions/cache@v1
                 with:
                      path: ~/.npm
                      key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                      restore-keys: |
                           ${{ runner.os }}-node-
               - name: use node js
                 uses: actions/setup-node@v1
                 with:
                      node-version: "12.x"
               - run: npm install
               # - run: npm run format:check
               - run: npm test -- --coverage
                 env:
                      CI: true
               - name: artifact for coverage
                 uses: actions/upload-artifact@v1 
                 with:
                   name: coverage
                   path: coverage                   
               - name: create build
                 if: github.event_name == 'push'
                 run: npm run build
               - name: artifact for build
                 if: github.event_name == 'push'
                 uses: actions/upload-artifact@v1 
                 with:
                   name: build
                   path: build 
               - name: create a release
                 if: github.event_name == 'push' && github.ref == 'refs/heads/master'
                 run: npx -p node@v18-lts -c "npx semantic-release"                   
               - name: deploy to staging
                 if: github.event_name == 'push'
                 run: npx surge --project ./build --domain youthful-edge.surge.sh
                 env:
                      SURGE_LOGIN: "${{ secrets.SURGE_LOGIN }}"
                      SURGE_TOKEN: "${{ secrets.SURGE_TOKEN }}"
